
builds:
  - id: node-zone-controller
    main: ./cmd/controller
    ldflags:
      - "-s -w"
    env:
      - CGO_ENABLED=0

defaultBaseImage: gcr.io/distroless/static-debian12@sha256:5c7e2b465ac6a2a4e5f4f7f722ce43b147dabe87cb21ac6c4007ae5178a1fa58
defaultPlatforms:
  - linux/arm64
  - linux/amd64
